name = "${{ secrets.CLOUDFLARE_PROJECT_NAME }}"
type = "javascript"
zone_id = ""
account_id = "${{ secrets.CLOUDFLARE_ACCOUNT_ID }}"
route = ""
workers_dev = true

[build]
command = "npm install && npm run build"
[build.upload]
format = "service-worker"
