name: Deploy

on:
    push:
        branches:
            - main

    workflow_dispatch:
        inputs:
            DEPLOYMENT_ENVIRONMENT:
                description: 'Deployment environment'
                required: true
                type: choice
                options:
                    - preview
                    - production
                default: 'production'

env:
    CLOUDFLARE_API_TOKEN: ${{ secrets.CLOUDFLARE_API_TOKEN }}
    CLOUDFLARE_ACCOUNT_ID: ${{ secrets.CLOUDFLARE_ACCOUNT_ID }}
    CLOUDFLARE_PROJECT_NAME: ${{ secrets.CLOUDFLARE_PROJECT_NAME }}
    DEPLOYMENT_ENVIRONMENT: ${{ inputs.DEPLOYMENT_ENVIRONMENT }}
    PRODUCTION_BRANCH: main

jobs:
    deploy:
        runs-on: ubuntu-latest
        name: deploy
        environment:
            name: ${{ github.event.inputs.DEPLOYMENT_ENVIRONMENT }}
        steps:
            - name: Checkout
              uses: actions/checkout@v3
            - name: Build and Publish [${{ inputs.DEPLOYMENT_ENVIRONMENT }}]
              uses: cloudflare/wrangler-action@1.3.0